### DISCUSSION TITLE
Use ReactJS and Tailwind css to create flip cards with video on every flip card

### DISCUSSION THREAD

**Discussion by HeeteshSimon** [EddieHubCommunity/support#133] [Ideas]
Using React and Tailwind css to create flip cards, which will have different videos on every flip card. 
What will be the alternative and easiest STACK that can be used for this?

**Comment by eddiejaoude** [comment]
This is quite a general question, which makes it more difficult for people to answer. But I will try. You don't need either of those, you can do it with html and css, here is an example I got from google https://www.w3schools.com/howto/howto_css_flip_card.asp 

![flip](https://user-images.githubusercontent.com/624760/91812962-d59ef480-ec29-11ea-8afc-65f73d239ecd.gif)


```html
<div class="flip-card">
  <div class="flip-card-inner">
    <div class="flip-card-front">
      <img src="img_avatar.png" alt="Avatar" style="width:300px;height:300px;">
    </div>
    <div class="flip-card-back">
      <h1>John Doe</h1> 
      <p>Architect & Engineer</p> 
      <p>We love that guy</p>
    </div>
  </div>
</div>
```

```css
/* The flip card container - set the width and height to whatever you want. We have added the border property to demonstrate that the flip itself goes out of the box on hover (remove perspective if you don't want the 3D effect */
.flip-card {
  background-color: transparent;
  width: 300px;
  height: 200px;
  border: 1px solid #f1f1f1;
  perspective: 1000px; /* Remove this if you don't want the 3D effect */
}

/* This container is needed to position the front and back side */
.flip-card-inner {
  position: relative;
  width: 100%;
  height: 100%;
  text-align: center;
  transition: transform 0.8s;
  transform-style: preserve-3d;
}

/* Do an horizontal flip when you move the mouse over the flip box container */
.flip-card:hover .flip-card-inner {
  transform: rotateY(180deg);
}

/* Position the front and back side */
.flip-card-front, .flip-card-back {
  position: absolute;
  width: 100%;
  height: 100%;
  -webkit-backface-visibility: hidden; /* Safari */
  backface-visibility: hidden;
}

/* Style the front side (fallback if image is missing) */
.flip-card-front {
  background-color: #bbb;
  color: black;
}

/* Style the back side */
.flip-card-back {
  background-color: dodgerblue;
  color: white;
  transform: rotateY(180deg);
}
```
