### DISCUSSION TITLE
Overlay not covering full screen

### DISCUSSION THREAD

**Discussion by numanjvd82** [EddieHubCommunity/support#87] [Q&A] [answered]
I have an overlay on my background image which doesn't cover the full screen

![Capture2](https://user-images.githubusercontent.com/30983365/90978308-542ece80-e566-11ea-9203-a424946bffb8.JPG)

CSS code for the overlay

```css
body::after {
  content: '';
  position: absolute;
  top: 0;
  bottom: 0;
  width: 100%;
  height: 100%;
  z-index: -1;
  background: rgba(0, 0, 0, 0.4);
  -webkit-box-shadow: inset 120px 100px 250px #000000;
  box-shadow: inset 120px 100px 250px #000000;
}
```
